### ISSUE TITLE
Error in "Sosa Configuration"

### ISSUE THREAD

**Issue by hartenthaler** [jon48/webtrees-geneajaubart#8]
When configuring the "Sosa Configuration": I selected the root person and clicked on "compute", then I got an error signal beside the compute button with no further information. Then I clicked on "save" and again on "compute" - now I got "success". Maybe compute should be invisible or greyed out until "save" was pressed.

**Comment by jon48** [comment]
Actually, in the general case, you case use the "Compute" button without clicking on the "Save" button first.
What you are experiencing is an initialisation "issue" : a root person needs to be defined before you can use most of the features of the Sosa module, so you should not really try to click on the Compute button before having defined a root.

I agree that the UI could be a bit more helpful in describing that issue, but this is not something I have spent much time on, as I see it as a edge case, and the form is a bit more complex than it looks. I will have a look at the next upgrade if there is a quick fix I can apply.

(A bit of an advance notice about this repository: I am happy to share those customisations that I have ported across the different versions of PhpGedView & webtrees, but it has never been my objective to deliver a package supported beyond my own usage, so whereas I am glad to hear about issues and ideas, I am not taking any commitment to address them 😃 )

**Comment by hartenthaler** [comment]
It is absolutely ok that you support your own usage only. Take my issues as an idea from the outside. For me, your own webtrees ecosystem is a chance to get ideas about what can be implemented differently.

**Comment by jon48** [comment]
That is a quick fix actually, I will ship it with the next 2.1.6 release.

**Comment by jon48** [comment]
>  For me, your own webtrees ecosystem is a chance to get ideas about what can be implemented differently.

In the past, I had to customise more heavily the core code, but the 2.0 stream has significantly improved the situation for custom modules, and there are more entry points.

However, I feel there are still 2 limiting factors (but there are difficult to address, and I do not necessarily have solutions for them) :

- The management of dependencies of the custom modules.
  - When building more complex modules, the need for additional vendor libraries can arise, and adding them to the standard ones can prove difficult when trying to create independent, ZIP-distributable packages. There are workarounds to load them, but I have not found a "safe" enough way to prevent conflicts either with the base package and/or other custom modules.
  - As I have shared components between my modules, I want to avoid duplicating code, and load it from a common library, and there are several approaches to do it. I have chosen the common "external" library way `webtrees-lib`, which comes back to the point above; that could be done as well through a common module but webtrees is not great yet at managing dependencies between modules (Richard has done a good attempt with the Vesta modules, but he has to replicate a lot of boilerplate in each module to manage it, and I am sure he would prefer to have webtrees doing this job more organically)

- Customisation of the UI
  - Again, there have been improvements with the 2.0 stream, but it has not resolved some of my goals. The big improvement was the ability to overwrite views, and progressively they are more and more compartmentalised, so that we do not have to copy large chunks of views in the modules just to change a minor thing in the view.
  - However, that is still not perfect as different custom modules may want to overwrite the same view, and there is no resolution mechanism for that (the latest module wins), so it is not stability-safe. And overwriting is not always the goal, we just want modules to "extend" a specific piece of the UI (like we can extend the menu, the tab list, the sidebar...), What I think is missing is more entry points for extension.
  - That is what I am trying to address with my Hooks mechanism (which are the only part where I interfere with the core code). The principle is similar to menu/tabs/sidebar, whereas modules register for a specific hook type, and when this hook is called, the input goes through the registered modules and an additional HTML code is returned (or alternatively, an object is manipulated and returned). For the purpose of my modules, the extension points are : adding information to the record name display (I add icons to quickly tag some individuals), adding other section to the individual name accordion (I am adding a title section), customising note/source title in facts, and datatable customisation.
  - Datatable customisation is quite a messy hook. and I would prefer a "Datatable builder" was introduced, which would allow to define columns and their content before being rendered, so that modules could add some additional columns more easily. This would be a major rewrite of the datatables logic though, maybe one day I will try to work on it and get in the core webtrees, but I am not even sure Greg will have much appetite for something that will probably be convoluted.

**Comment by hartenthaler** [comment]
Thank you very much for sharing your thoughts! Very interesting.

I have seen already many changes you have made to improve for example data tables. I like to play a bit more with your version of webtrees.

Have you ever thought about separating some of your functions/modules that are less dependent on other custom modules and do not necessarily need to use your Hooks mechanism in order to publish them as separate webtrees custom modules? For example, your main menu Sosa module would be very interesting for many webtrees users.

**Comment by jon48** [comment]
> Have you ever thought about separating some of your functions/modules that are less dependent on other custom modules and do not necessarily need to use your Hooks mechanism in order to publish them as separate webtrees custom modules?

Yes, I have, and technically, I have built each module so that they can still run (with limited features) without each other, or the core changes. The Sosa module, for instance, would not display icons next to the name, but the list pages, and Sosa statistics could still be displayed.

There are still dependencies to some shared classes, and external libraries not shipped with webtrees, so I need to find an approach I am comfortable with to my first point in my previous comment.

This will probably be my next big project to split this repository and the [jon48/webtrees-lib](https://github.com/jon48/webtrees-lib) one into separate modules, now that I am done with the webtrees 2 migration (hoping that Greg is not going to move to a webtrees 3 too quickly :sweat_smile: )
